before_script:
  - cd blatt4

Kompilieren mit Gradle:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:7.4.2-jdk11
  script:
    - gradle compileJava

Testen mit Gradle:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:7.4.2-jdk11
  script:
    - gradle test
